const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const read = (file) => fs.readFileSync(path.join(projectRoot, file), "utf8");
const html = read("index.html");
const styles = read("styles.css");
const projectStyles = read("project.css");
const access = read("access.js");
const productScript = read("script.js");
const projectScript = read("project.js");
const allPublicSource = [html, styles, projectStyles, access, productScript, projectScript].join("\n");

assert.match(html, /id="access-gate"/);
assert.match(html, /meta name="robots" content="noindex, nofollow, noarchive"/);
assert.match(html, /rel="icon" href="assets\/favicon\.svg"/);
assert.ok(fs.statSync(path.join(projectRoot,"assets","favicon.svg")).size>100,"favicon.svg should be present");
assert.match(access, /crypto\.subtle\.digest\("SHA-256"/);
assert.match(access, /sessionStorage\.setItem/);
assert.match(styles, /\.hero\{height:100svh;min-height:680px/);
assert.doesNotMatch(allPublicSource, /by [A-Z][A-Z ]+TILE/);
assert.doesNotMatch(html, /https:\/\/[^\s"']*tile[^\s"']*\.jp/i);
assert.match(html, /class="product-code"/);
assert.match(html, /class="product-thickness"/);
assert.match(html, /class="product-favorite"/);
assert.match(html, /data-open-favorites>FAVORITES/);
assert.match(html, /class="favorites-view" id="favorites"/);
assert.match(html, /class="favorites-grid" aria-live="polite"/);
assert.match(html, /class="favorites-empty" hidden/);
assert.match(html, /class="dark-link dialog-sample"/);
assert.match(html, /class="text-link dialog-space-link"/);
assert.match(productScript, /code:"HT-TRV-6012-WG"/);
assert.match(productScript, /image:"assets\/tile-travertine\.jpg"/);
assert.match(productScript, /thickness:"9 mm"/);
assert.match(productScript, /use:\["Floor","Wall","Interior"\]/);
assert.match(productScript, /description:"自然な層/);
assert.match(productScript, /const FAVORITES_STORAGE_KEY="tiles-space-favorites"/);
assert.match(productScript, /new Set\(Array\.isArray\(stored\)\?stored\.filter/);
assert.match(productScript, /data-favorite-action="remove"/);
assert.match(productScript, /function openSampleRequest\(product\)/);
assert.match(productScript, /if\(location\.hash==='\#favorites'\)openFavorites\(\)/);
assert.match(projectStyles, /\.favorites-grid\{display:grid;grid-template-columns:repeat\(3/);
assert.match(projectScript, /addEventListener\('open-project'/);
assert.match(projectScript, /addEventListener\('close-project'/);
["tile-travertine.jpg","tile-deep-stone.jpg","tile-craft-clay.jpg","tile-soft-limestone.jpg"].forEach((file)=>{
  assert.ok(fs.statSync(path.join(projectRoot,"assets",file)).size>100000,`${file} should be a real product image`);
});

console.log("site.test.js: access gate, branding, and standalone layout checks passed");
